### ISSUE TITLE
disnake.VoiceChannel.pins()

### ISSUE THREAD

**Issue by solumath** [DisnakeDev/disnake#1033]
### Summary

VoiceChannel.pins method for nonexistent pins

### What is the feature request for?

The documentation

### The Problem

Not sure if this is intentional but existence of `disnake.VoiceChannel.pins()` makes me think that voice channels can have pins. Executing the method will always return empty list so there's no need for it. And you can't pin messages in voice channels.

### The Ideal Solution

Hint that voice channels don't have pins? Might delete the method?

**Comment by shiftinv** [comment]
Yeah, good catch. `pins()` is implemented on `Messageable`, so all messageable channels automatically get that method, even though voice and stage channels technically don't support it.
I'll update the docs for now to exclude the method there. This can eventually be fixed more easily through a refactor of the channel type hierarchy.
