### ISSUE TITLE
Add support for scheduled guild events

### ISSUE THREAD

**Issue by jgayfer** [DisnakeDev/disnake#106]
### Summary

Discord is rolling out scheduled events, which the library should support.

Relevant docs API PR: https://github.com/discord/discord-api-docs/pull/3586

**Comment by EQUENOS** [comment]
Thank you for this information, I'm going to implement this soon!

**Comment by abhigyantrips** [comment]
An update on this issue - some breaking changes are still being made to the methods/event names for Scheduled Events (Refer [this PR](https://github.com/discord/discord-api-docs/pull/3586)). 

So, development and implementation of the same will be delayed a little, until things are finalized.

**Comment by Victorsitou** [comment]
#110 is already merged, so this issue should be closed now.

**Comment by shiftinv** [comment]
This is fully implemented and will be released as part of v2.3.0.
