### ISSUE TITLE
disnake:Member object, attribute guild_permissions dont have attribute "timeout_members"

### ISSUE THREAD

**Issue by UndoGG** [DisnakeDev/disnake#1065]
### Summary

Timeout members error

### Reproduction Steps

(Code in my discord-bot to check permissions)
import disnake

async def run(interaction: disnake.CommandInteraction):
    if interaction.author.guild_permissions.timeout_members:
        print('You have permissions!')
    else:
        print('You have\'nt this permission!')

### Minimal Reproducible Code

```python
if interaction.author.guild_permissions.timeout_members:
```

### Expected Results

if interaction.author.guild_permissions.timeout_members returns False or True

### Actual Results

if interaction.author.guild_permissions.timeout_members
disnake.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'Permissions' object has no attribute 'timeout_members'

### Intents

all

### System Information

```markdown
- Python v3.11.3-final
- disnake v2.8.1-final
    - disnake importlib.metadata: v2.8.1
- aiohttp v3.8.4
- system info: Windows 10 10.0.22621 AMD64
```

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by shiftinv** [comment]
The permission you're looking for is `moderate_members`, as seen e.g. here: https://docs.disnake.dev/en/stable/api/members.html#disnake.Member.timeout - this matches the [official](https://discord.com/developers/docs/topics/permissions) naming.
