### ISSUE TITLE
Add jump_url to user

### ISSUE THREAD

**Issue by BazZziliuS** [DisnakeDev/disnake#1099]
### Summary

user.jump_url

### What is the feature request for?

The core library

### The Problem

I often use this to leave a fixed link to the user because mention sometimes does not load and looks just like text ``<@123456789>``

### The Ideal Solution

integrate into user
It should return the following text ``https://discord.com/users/{user_id}``

### The Current Solution

I'm still using this
```
def jump_dm_discord(user_id) -> str:
    return f'https://discord.com/users/{user_id}'
```

### Additional Context

I believe that this function will not cause you any trouble

**Comment by shiftinv** [comment]
Deep-linking user profiles has unfortunately never worked consistently on all platforms. As far as I can tell, this currently only works on mobile, so it's not something we should add at this time.
See also https://github.com/discord/discord-api-docs/discussions/5183
