### ISSUE TITLE
Add 2 important colors

### ISSUE THREAD

**Issue by BazZziliuS** [DisnakeDev/disnake#1100]
### Summary

Add 2 colors

### What is the feature request for?

The core library

### The Problem

I suggest adding 2 colors
1. Embed background color `0x2B2D31`
2. Nitro color `0xf47fff`

### The Ideal Solution

Integration of colors in disnake.Color

### Additional Context

There is a great lack of these colors

**Comment by shiftinv** [comment]
I don't think there are official nitro colors, and couldn't find the one you mentioned - the most common one based on color picking various places in the client seems to be `0xff74fa`, but even that isn't being used consistently.
#1102 adds the embed background color for both light and dark themes.
