### ISSUE TITLE
Expose enums off relevant classes' namespace

### ISSUE THREAD

**Issue by Enegg** [DisnakeDev/disnake#1114]
### Summary

Allow to reference `ButtonStyle` as `Button.Style` etc.

### What is the feature request for?

The core library

### The Problem

The library defines various enums in the `disnake.enums` module. Most of those enums are relevant only in companion of a specific class/object.

Typically, those enums' names consist of the name of the object they are relevant to, and the name of a parameter they parametrize, ex. `ButtonStyle`, `TextInputStyle`. This further indicates the access to those enums should be provided off the relevant class.

### The Ideal Solution

There's a pattern in other languages to contain the definition of an enum within the namespace of the relevant class.
The classes could be redefined as such:
```py
class Button:
    class Style(Enum):
        secondary = ...
        primary = ...

    def __init__(self, *, style: Style = Style.secondary, ...) -> None:
        ...

my_button = Button(style=Button.Style.primary)

# possibly, to avoid breaking changes:
# enums.py
from components import Button

ButtonStyle = Button.Style
```
This is a more demanding and possibly breaking change, but it explicitly couples the relation of the enums to the classes.

If it is decided that the cons of breaking changes outweigh benefits, the feature could be implemented free of breaking changes as such:
```py
from disnake.enums import ButtonStyle
import typing

class Button:
    Style: typing.Final[typing.ClassVar] = ButtonStyle

my_button = Button(style=Button.Style.primary)
```
Note that in particular for members of `.components` and `.ui`, the enums should probably be provided off both corresponding members.

### The Current Solution

Monkey-patching/subclassing existing classes, or doing it the so-far way of importing the enums separately.

**Comment by EmreTech** [comment]
This looks like a good idea for organization, but I think it's unnecessary and has a few big flaws. Where would enums referenced by multiple classes go? Plus, as mentioned on the Discord server, the possible import cycles this could cause.

**Comment by shiftinv** [comment]
Thanks for the feature request! While not a bad idea in itself, this pattern seems somewhat unusual in Python; as you mentioned, one might expect something like it in Java or C#, but overall this doesn't seem to provide many advantages over existing code.
The first proposal/example gets very tricky due to circular imports, especially when adding the `from components import Button` part. The second proposal/example seems much more doable, but even then, having two distinct ways to reference this enum will only make things more confusing to some users.

**Comment by Enegg** [comment]
Thanks for constructive response.

I don't buy the argument of not doing something due to the change being "not pythonic", however I understand how the change gives few advantages in a rather mature project.

PS.
Are there better places such ideas can be discussed (on github), or is making issues the way to go?

**Comment by shiftinv** [comment]
> PS.
> Are there better places such ideas can be discussed (on github), or is making issues the way to go?

Ah, good call. On github, [discussions](https://github.com/DisnakeDev/disnake/discussions) work well for talking about new ideas or bikeshedding existing things, but issues are perfectly fine as well. Those can also be converted into discussions when needed, but the medium ultimately doesn't really matter, new ideas are always welcome c:
