### ISSUE TITLE
Ignoring i18n files starting with .

### ISSUE THREAD

**Issue by OseSem** [DisnakeDev/disnake#1182]
### Summary

This feature will ignore all the files in a folder that gets loaded with i18n files

### What is the feature request for?

The core library

### The Problem

When loading locale files I had a template file that started with a dot. Because of this I had to move it to another folder. But this could have been fixed by a simple startswith check.

I could make this for you guys if needed.

### The Ideal Solution

The function ignores the i18n file using a `.startswith(“.”)`

**Comment by elenakrittik** [comment]
I think this is not needed in core, as this can be easily implemented manually (`path.glob` + `if .startswith("."): continue` + `bot.i18n.load`).

**Comment by OseSem** [comment]
I will close this as I have already found a solution.
