### ISSUE TITLE
Local embed icons

### ISSUE THREAD

**Issue by MofiYy** [DisnakeDev/disnake#1184]
### Summary

Using local icons in embed

### What is the feature request for?

The core library

### The Problem

The problem is using icons in set_author (it only supports icon links), but I would like to simplify the interaction with icons and add the ability to insert local icons that are stored with the bot code.

### The Ideal Solution

Adding local icons to author will give a more convenient interaction of the developer with his created icons + simplify the storage of icon data, you will not have to look for third-party services for this + thereby speed up the process of executing a command with these icons, this mechanics is localized in the hikari library.

I wish we could pass the path to our icon. Which can have a completely different format, PNG values ending with WEBP

**Comment by Enegg** [comment]
You should be able to upload an attachment and set the icon url to `attachment://...`

**Comment by OseSem** [comment]
> You should be able to upload an attachment and set the icon url to `attachment://...`

You can but it is a hastle and being able to add a `disnake.File` or local file would be nice
