### ISSUE TITLE
Discord gives error if integer is too high

### ISSUE THREAD

**Issue by Luckstern** [DisnakeDev/disnake#123]
### Summary

When assigning a slash command parameter to and integer and then putting a really long number as the parameter in your Discord client, Discord will give an error.

### Reproduction Steps

1. Use code snippet to create bot
2. Run the code
3. Add bot to server with appropriate permissions and scopes
4. Run slash command and set the integer parameter to a really long number like 900384081332797542

### Minimal Reproducible Code

```python
import disnake
from disnake.ext import commands

bot = commands.Bot(command_prefix=';')

@bot.slash_command(name='test', description='Test command for long number')
async def test(inter, integer: int):
  await inter.response.send_message('Test succesful')

bot.run('TOKEN')
```

### Expected Results

I expected the number to be usable. The integer is an emoji id so it's going to be unavoidably long.

### Actual Results

Discord rejected then number. I don't know if this is a problem with this library or some limitation with Discord though.

### Intents

None

### System Information

- Python v3.8.6-final
- disnake v2.2.1-beta
    - disnake pkg_resources: v2.2.1
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.19041

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

If something doesn't make sense, I can clarify.

**Comment by jgayfer** [comment]
The max int value is `2^53`, which `900384081332797542` is larger than. This is a Discord limitation, not a problem with the library. You'll need a text input if you need a number larger than this.

See [the docs](https://discord.com/developers/docs/interactions/application-commands#application-command-object-application-command-option-type) for more information.

**Comment by Luckstern** [comment]
Ah, thank you for the quick reply. I guess I'll have to stick with a string. This issue is resolved.

**Comment by thesadru** [comment]
Please use `emoji: disnake.Emoji` in your command. It will automatically convert any kind of string to an emoji if possible.
