### ISSUE TITLE
Default values does not work

### ISSUE THREAD

**Issue by Ayomits** [DisnakeDev/disnake#1251]
### Summary

When I use ChannelSelect class or another where I can use default_values in Discord API. I cannot do that

### Reproduction Steps

1) use class ChannelSelect from disnake.ui.select
2) Try to use default_values parametr

### Minimal Reproducible Code

```python
channel_select = ChannelSelect(
            custom_id=custom_id,
            channel_types=channel_types or [],
            min_values=0,
            max_values=25,
            placeholder=placeholder,
            default_values=default_channels
        )
        
        
    You will get this error:
    
    

    TypeError: ChannelSelect.__init__() got an unexpected keyword argument 'default_values'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\projects\Celestial\celestial_py\venv\Lib\site-packages\disnake\ext\commands\interaction_bot_base.py", line 1378, in process_application_commands
    await app_command.invoke(interaction)
  File "E:\projects\Celestial\celestial_py\venv\Lib\site-packages\disnake\ext\commands\slash_core.py", line 737, in invoke
    raise CommandInvokeError(exc) from exc
disnake.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: ChannelSelect.__init__() got an unexpected keyword argument 'default_values'
```

### Expected Results

Must be select menu with default selected values

### Actual Results

TypeError: ChannelSelect.__init__() got an unexpected keyword argument 'default_values'

### Intents

all

### System Information

```markdown
PS E:\projects\Celestial\celestial_py> python -m disnake -v
- Python v3.12.6-final
- disnake v2.9.3-final
    - disnake importlib.metadata: v2.9.3
- aiohttp v3.11.7
- system info: Windows 10 10.0.19045 AMD64
PS E:\projects\Celestial\celestial_py>
```

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by shiftinv** [comment]
Looks like this was resolved in [this help thread](https://canary.discord.com/channels/808030843078836254/1310276385432145990) already. To summarize, default values for these auto-populated select menus are not available in the latest release (v2.9.3) yet, only in the current development version, which can be installed directly from GitHub.
