### ISSUE TITLE
Add a shortcut for `User.name + str(User.discriminator)`

### ISSUE THREAD

**Issue by weerdy15** [DisnakeDev/disnake#128]
### Summary

Add a shortcut for `User.name + str(User.discriminator)`

### What is the feature request for?

The core library

### The Problem

It is inconvenient to write every time you want to show user's full nickname `user.name + str(user.discriminator)`
I want to something like [`.tag` attribute in discord.js](https://discord.js.org/#/docs/main/stable/class/User?scrollTo=tag)

### The Ideal Solution

None

**Comment by m1raynee** [comment]
str(user)
