### ISSUE TITLE
Return a disnake.Message object when inter.send() -ing

### ISSUE THREAD

**Issue by PetitPotiron** [DisnakeDev/disnake#144]
### Summary

Doing ctx.send with disnake.Context returns a disnake. Message object, while inter.send doesn't return anything. I suggest to return the message

### What is the feature request for?

The core library

### The Problem

Disclaimer: I'm going to use `ctx` as a keyword, but that's still an interaction.
If I use `ctx.send('Hello world')` in a message command (with `disnake.Context`), the method returns a `disnake.Message`.
In the contrary, using `ctx.send('Hello world')` in a slash command, component... (with `disnake.Interaction`), the method doesn't return anything. 

### The Ideal Solution

Using `ctx.send('Hello world')` with `disnake.Interaction` returns a `disnake.Message` object.

### The Current Solution

Using `ctx.send('Hello world')` with `disnake.Interaction` doesn't return anything (because the API doesn't return anything, I consider fetching the message after sending it to return an object).

**Comment by Victorsitou** [comment]
`disnake.Interaction.send` doesn't return Message object because of API limitations, as far as I know.

**Comment by thesadru** [comment]
The message is not actually needed in any way. To do anything with it you may simply use `interaction.edit_original_message` or `interaction.delete_original_message`

**Comment by shiftinv** [comment]
Indeed, the API doesn't return the message when responding to application command interactions. This is intended behavior, if you really need a message object and `edit_original_message`/`delete_original_message` isn't an option for you, use `await ctx.original_message()`.

**Comment by PetitPotiron** [comment]
I think I badly explained. I want to get the **interaction response** message.

**Comment by Victorsitou** [comment]
> I think I badly explained. I want to get the **interaction response** message.

If I understand correctly, the best solution for you would be `await ctx.original_message()`, which fetches and returns the original message. [Link to documentation.](https://disnake.readthedocs.io/en/latest/api.html#disnake.Interaction.original_message)

**Comment by PetitPotiron** [comment]
> 
> 
> Indeed, the API doesn't return the message when responding to application command interactions. This is intended behavior, if you really need a message object and `edit_original_message`/`delete_original_message` isn't an option for you, use `await ctx.original_message()`.



> 
> 
> > I think I badly explained. I want to get the **interaction response** message.
> 
> If I understand correctly, the best solution for you would be `await ctx.original_message()`, which fetches and returns the original message. [Link to documentation.](https://disnake.readthedocs.io/en/latest/api.html#disnake.Interaction.original_message)

That's exactly what I want, thanks for your help.
