### ISSUE TITLE
Add support for Guild time outs.

### ISSUE THREAD

**Issue by Victorsitou** [DisnakeDev/disnake#155]
Discord is experimenting with this new feature which is basically like a Muted role but even better and easier.

This is something that the library should really support.

ref:
https://github.com/discord/discord-api-docs/pull/4075

**Comment by onerandomusername** [comment]
They've also added a new permission, 1 << 40 which is manage members. I think that should be added as a new permission even without full timeout support, perhaps as a mini pr before the full timeout support pr.

**Comment by Victorsitou** [comment]
> They've also added a new permission, 1 << 40 which is manage members. I think that should be added as a new permission even without full timeout support, perhaps as a mini pr before the full timeout support pr.

I know, but that permission is really useless if the time outs feature isn't released :/

**Comment by onerandomusername** [comment]
IMO it's not useless since commands which mutate roles can still mutate roles and gather info on the roles w/out being able to timeout users.

**Comment by Victorsitou** [comment]
> IMO it's not useless since commands which mutate roles can still mutate roles and gather info on the roles w/out being able to timeout users.

Hmm yeah, but that permissions isn't in the stable version, is it?

**Comment by onerandomusername** [comment]
AFAIK it is, not sure atm since I'm on mobile.

**Comment by Victorsitou** [comment]
> AFAIK it is, not sure atm since I'm on mobile.

I just checked it and it isn't in stable, so I don't see why implementing that yet.

**Comment by onerandomusername** [comment]
Okay, yeah, its not officially documented yet either. https://discord.com/developers/docs/topics/permissions#permissions-bitwise-permission-flags
