### ISSUE TITLE
Add support for thread rate limits

### ISSUE THREAD

**Issue by jgayfer** [DisnakeDev/disnake#158]
### Summary

A new field was added to the thread creation endpoints, which we should support

### What is the feature request for?

The core library

### The Problem

We're not fully covering the threads API.

Docs commit here: https://github.com/discord/discord-api-docs/commit/d56be860c5dd4c04e80337556d82eb3a04f971a2

### The Ideal Solution

Add support for the new field.

### Additional Context

This is a fairly straight forward change, and is a good issue for a new contributor to tackle.

**Comment by Victorsitou** [comment]
#132 already supports it, if I understand correctly.
