### ISSUE TITLE
Fix docs for `Color`

### ISSUE THREAD

**Issue by shiftinv** [DisnakeDev/disnake#167]
Search doesn't come up with any results since `Color` is just aliased to `Colour`:
https://docs.disnake.dev/en/latest/search.html?q=Color.blurple
https://github.com/DisnakeDev/disnake/blob/860bede15391cdbf9b048359c48e1b66ad826cee/disnake/colour.py#L333

**Comment by thesadru** [comment]
[relevant project card](https://github.com/DisnakeDev/disnake/projects/1#card-73214402)

**Comment by Victorsitou** [comment]
I already have an implementation for that, I will commit it in #153.

**Comment by eibex** [comment]
> Update: it looks like sphinx/rtd doesn't have an alias thing, so I decided to directly do it in the JavaScript

As I told both shiftinv and Victorsitou earlier I didn't find any fuzzy/alias search for sphinx. The JS implementation looks like the cleanest solution to avoid making duplicate entries for `Color` and `Colour`.
