### ISSUE TITLE
Add slash commands permissions 

### ISSUE THREAD

**Issue by PetitPotiron** [DisnakeDev/disnake#171]
### Summary

Discord added a way to provide slash commands for only some of the users.

### What is the feature request for?

disnake.ext.commands

### The Problem

Discord added a way to provide slash commands for only the members who have the [permission](https://discord.com/developers/docs/interactions/application-commands#permissions). Currently, we can't use this feature with the library.

### The Ideal Solution

I would like the library to add a `permission` parameter to the `commands.slash_command` object, to use this feature.

### Additional Context

[Discord API for permissions](https://discord.com/developers/docs/interactions/application-commands#permissions)

**Comment by Victorsitou** [comment]
You can use the decorator `@commands.has_*`.

docs: https://docs.disnake.dev/en/latest/ext/commands/api.html#checks

**Comment by shiftinv** [comment]
Server-side permissions can already be set manually, or using the [`commands.guild_permissions`](https://docs.disnake.dev/en/latest/ext/commands/api.html?highlight=guild_permissions#disnake.ext.commands.guild_permissions) decorator.
There currently isn't a concrete example for it yet, but the basic idea is this:
https://github.com/DisnakeDev/disnake/blob/f8c6c58ebfaf2072235268ca7eea03824f191040/tests/cogs/slash_commands.py#L32-L34
