### ISSUE TITLE
Known bug with cogs context menus commands on Python 3.10

### ISSUE THREAD

**Issue by Victorsitou** [DisnakeDev/disnake#174]
### Summary

It seems that context menus commands in cogs aren't working on Python 3.10. 

However, the current GitHub version seems to fix that, so I'll leave this issue just to make sure it's a known bug, but this will be fixed in the next version. (Probably 2.3)

shiftinv figured out why it was happening, full conversation [here](https://canary.discord.com/channels/808030843078836254/883342278280745030/914682454097416212).

**Comment by shiftinv** [comment]
relevant cpython commit: https://github.com/python/cpython/commit/b5cc2089cc354469f12eabc7ba54280e85fdd6dc

**Comment by shiftinv** [comment]
This is already fixed on master through the use of `safe_call`, but it might be worth a separate patch for v2.2.x.

**Comment by Victorsitou** [comment]
This has been fixed in version 2.3.
