### ISSUE TITLE
Parsed channels in slash commands do not have any permission overwrite data

### ISSUE THREAD

**Issue by Kyzegs** [DisnakeDev/disnake#180]
### Summary

It seems that permission overwrite data is missing from guild channels when used with slash commands. `channel.overwrites` will always return an empty dictionary.

### Reproduction Steps

1). Create a slash command with a channel option
2). Check the overwrites for that channel

### Minimal Reproducible Code

```python
async def lock(
    self,
    interaction: disnake.ApplicationCommandInteraction,
    channel: disnake.TextChannel
) -> None:
    # Will always be {}
    print(channel.overwrites)
```

### Expected Results

To receive the permission overwrites for that channel.

### Actual Results

An empty dictionary at all times.

### Intents

NA

### System Information

- Python v3.8.6-final
- disnake v2.2.2-beta
    - disnake pkg_resources: v2.2.2
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.19041

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Victorsitou** [comment]
Yup, this seems to be a bug, a workaround for this could be to get the channel using `inter.guild.get_channel(channel.id)`.

We will work to fix this bug in the next version :)

**Comment by Kyzegs** [comment]
Yeah, I was already using a workaround. It's too bad Discord does not provide that data.

**Comment by onerandomusername** [comment]
I think the solution will be internally updating the channel from the cache before the callback is called, EQUENOS mentioned that in discord.
