### ISSUE TITLE
Write a new readme

### ISSUE THREAD

**Issue by onerandomusername** [DisnakeDev/disnake#185]
### Summary

Change the readme entirely to be different than the inherited readme

### What is the feature request for?

The documentation

### The Problem

Readme looks the same as every other fork.

### The Ideal Solution

New readme, new format, new examples. Showcase what disnake has to offer.

**Comment by abhigyantrips** [comment]
I get the general idea of what this is talking about. But I'll be honest, if this issue is going to bring a major change to the frontpage of the repo, it has to be a more descriptive/ planned out.

The "problem" doesn't make it seem like an issue - doesn't highlight *why* having the same README as other forks is troublesome (the obvious answer to include is "in order to stand out"). The solution also sounds incomplete.

My point is, make the issue more descriptive, as the change it will cause is quite major. The only message I get from the 5 lines currently written is, "Write a new readme".

**Comment by EQUENOS** [comment]
> My point is, make the issue more descriptive

The request is to rewrite the README, it's detailed enough imo. I also thought about rewriting readme actually

**Comment by abhigyantrips** [comment]
In that case, it'd still be a good idea to state in the issue, as to what we should include in the rewrite. Though we can just mention the pointers here ourselves, if you'd like. To keep all info in one place.

**Comment by thesadru** [comment]
I'd personally like to get rid of the prefix command examples (everyone has those anyways) and instead keep only slash commands and ctx menu commands. Slash commands should also have at least one option since that's generally where the biggest difference between forks comes in.

**Comment by Hunter2807** [comment]
> I'd personally like to get rid of the prefix command examples (everyone has those anyways) and instead keep only slash commands and ctx menu commands. Slash commands should also have at least one option since that's generally where the biggest difference between forks comes in.

Well I don't agree with this since there can be people in the future who don't use discord.py but start their bot making journey with disnake itself. Then, it's gonna be difficult for them to get started since examples really help a lot to understand a lotta things

**Comment by abhigyantrips** [comment]
> There can be people in the future who don't use discord.py but start their bot making journey with disnake itself. Then, it's gonna be difficult for them to get started since examples really help a lot to understand a lot of things

I agree with this. We can keep the example below application commands, ofcourse. But the syntax that different parts of the library use *should* be displayed in the front page of the library.

**Comment by onerandomusername** [comment]
> My point is, make the issue more descriptive, as the change it will cause is quite major. The only message I get from the 5 lines currently written is, "Write a new readme".

@abhigyantrips I don't have any ideas for a new readme, but someone pointed out to me that it looks the same as every other fork when trying to determine which fork they should use, so I thought I would bring that up.
