### ISSUE TITLE
Lower level component interface

### ISSUE THREAD

**Issue by onerandomusername** [DisnakeDev/disnake#195]
### Summary

lower level component iterface that doesn't involve views

### What is the feature request for?

The core library

### The Problem

disnake.ui.View requires a lot of code for some complex features. I'd like to be able to use components at a lower level. Because on_message_interaction exists in the dispatched events, that is usable after sending the component. However, a view has to be used to send components with disnake.abc.Messegeable.send

### The Ideal Solution

A solution here seems like it would be in the source of send, to expose `components` as a kwarg, and document how to pass buttons and the like to that.

### The Current Solution

Make a view and send that, but then intercept the params with on_message_component.

**Comment by EQUENOS** [comment]
We will receive tons of hate for supporting `components` kwarg together with views
