### ISSUE TITLE
Stateless permanent component handlers

### ISSUE THREAD

**Issue by thesadru** [DisnakeDev/disnake#198]
## Summary

We need a way to handle components without being forced to use a view.

## The Problem

Currently, a huge problem left over from discord.py is the enforced usage of views. Generally, most components could be handled using just information gotten from the interaction dispatched through the gateway. But instead, we are forced to use views that either timeout or make all views permanent which would however inevitably cause a memory leak. 

`on_message_interaction` is a very good alternative but it's missing highly needed abstraction.

## The Ideal Solution

Say we're working with a message that has an embed with a specific rule and buttons to get the previous (`custom_id="help:prev"`) and next rules (`custom_id="help:next"`) and a button to delete the message (`custom_id="delete"`).

### Pure component handlers

The simplest thing we could do is simply add our own built-in listener which dispatches other handlers. 

The usage would be as follows.
```py
def get_page(interaction: disnake.MessageInteraction) -> int:
    string = interaction.message.embeds[0].title
    return int(string.split(":")[0])

@commands.component("delete")
async def delete_message(interaction: disnake.MessageInteraction):
    await interaction.message.delete()
    await interaction.response.send_message("Deleted message", ephemeral=True)

@commands.component("help:next")
async def delete_message(interaction: disnake.MessageInteraction):
    page = get_page(interaction)
    embed = my_utils.get_rule_embed(page=page + 1)
    await interaction.response.edit_message(embed=embed)

@commands.component("help:prev")
async def delete_message(interaction: disnake.MessageInteraction):
    page = get_page(interaction)
    embed = my_utils.get_rule_embed(page=page - 1)
    await interaction.response.edit_message(embed=embed)
```

### State in custom_id

This solution would change custom_id handling to embed encoded data (for simplicity in the form of json here). The new custom ids would be as follows (assuming the current rule page is 2): `help:next#{"page":2}`

The usage would be as follows.
```py
# make this a custom class in the future maybe? More abstraction is always welcome
class PageButtonState(TypedDict):
    page: int

@commands.component("delete")
async def delete_message(interaction: disnake.MessageInteraction, state: Dict[str, Any]):
    await interaction.message.delete()
    await interaction.response.send_message("Deleted message", ephemeral=True)

@commands.component("help:next")
async def delete_message(interaction: disnake.MessageInteraction, state: PageButtonState):
    embed = my_utils.get_rule_embed(page=state["page"] + 1)
    await interaction.response.edit_message(embed=embed)

@commands.component("help:prev")
async def delete_message(interaction: disnake.MessageInteraction, state: PageButtonState):
    page = get_page(interaction)
    embed = my_utils.get_rule_embed(page=state["page"] - 1)
    await interaction.response.edit_message(embed=embed)
```

## The Current Solution

Enforced views / permanent views / low level event handling.low-level

```py
@listener()
async def on_message_interaction(interaction: disnake.MessageInteraction):
    custom_id = interaction.data.custom_id 

    if custom_id == "delete":
        await interaction.message.delete()
        await interaction.response.send_message("Deleted message", ephemeral=True)
    
    if custom_id not in ["help:next", "help:prev"]:
        return

    string = interaction.message.embeds[0].title
    page = int(string.split(":")[0])

    if custom_id == "help:next":
        page += 1
    if custom_id == "help:prev":
        page -= 1

    embed = my_utils.get_rule_embed(page=page)
    await interaction.response.edit_message(embed=embed)
```

## Additional Context

This is also being discussed over in the disnake discord server.

**Comment by onerandomusername** [comment]
related: #195

**Comment by jgayfer** [comment]
I like this general idea, especially the state in the ID 👍 

One thought though is that I'd want the state in the custom ID to be a little more permissive than simply JSON. For example, I have a large number of existing custom IDs in the wild of the form `delete:12345`, where `12345` is an ID of an internal resource I use.

Perhaps a way to define a regex in the custom ID to choose how the internal state is extracted?

**Comment by thesadru** [comment]
It should be possible to specify your own parser using annotations.

This is how one could implement a json state. (Just a rough idea, probably very bad)
```py
class JSONState(commands.BaseComponentState):
    def encode(self, custom_id: str):
        raw_custom_id =  custom_id + "#" + json.dumps(self.data)
        return raw_custom_id

    def decode(self, raw_custom_id: str):
        custom_id, self.data = raw_custom_id.split("#", 1)
        return custom_id
```

**Comment by EQUENOS** [comment]
I like the idea of states in custom IDs but this concept seems to be too much for the current length limits. Custom IDs can be only 100 characters long, it would be hard to dump too much data there (even with encoding tricks).

**Comment by EQUENOS** [comment]
Also I wanted to ask a question about your example. So we change the page number, does it mean that we have to edit all components with `...#{"page":2}` to `...#{"page":3}`?

**Comment by thesadru** [comment]
Yeah, that's the plan. Don't ask me how though.

**Comment by EQUENOS** [comment]
Well it's not too bad because you can edit all components in one API request

**Comment by onerandomusername** [comment]
While this has been added since disnake 2.4, I'm leaving this open for now, due to refactors to ActionRow in #462

**Comment by onerandomusername** [comment]
A community project over at https://github.com/DisnakeCommunity/disnake-ext-components has started to add the more creative ideas this pr suggests into their extension, and we have basic support for stateless component handlers. I'm marking this as closed, but this can be revisited in the future if more interest is expressed.
