### ISSUE TITLE
Disnake Guide Incomplete

### ISSUE THREAD

**Issue by sethpeace** [DisnakeDev/disnake#303]
### Summary

The Disnake Guide at https://guide.disnake.dev/interactions/message-components is incomplete

### Reproduction Steps

Go to https://guide.disnake.dev/interactions/message-components or https://guide.disnake.dev/interactions/application-commands and see the emptiness

### Expected Results

I expected to see example code and explanation

### Actual Results

I saw headers and thats it

### Intents

N/A

### System Information

Windows 10 - Opera GX

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by onerandomusername** [comment]
Hi, [there's a repo for the guide](https://git.disnake.dev/guide) and this is not that repo. Additionally, it's still a WIP, and as such we don't mention its existence in many places.

**Comment by abhigyantrips** [comment]
The guide is still a work in progress, as already mentioned in the README of its repo - https://github.com/DisnakeDev/guide .

<img width="660" alt="image" src="https://user-images.githubusercontent.com/28886624/150729142-85352e9b-10f3-4bc3-9cd5-6f137e1f3870.png">

This is not a bug, or unintentional. We're still working on the content, with no specific ETA on when it'll be complete.
