### ISSUE TITLE
Gateway ratelimiter is too strict when exhausting ratelimit in current window

### ISSUE THREAD

**Issue by shiftinv** [DisnakeDev/disnake#314]
### Summary
While working on #308 I noticed that the current `GatewayRatelimiter` seems to be ratelimiting too much once the number of commands for the current window is exhausted, which I also noted here:
https://github.com/DisnakeDev/disnake/blob/7112926e608ff2a8fa36cc94a801a5f2c3dc26c1/disnake/gateway.py#L170-L173

The gateway allows 120 commands/requests per 60 seconds, `GatewayRatelimiter` intentionally only allows 110 to leave room for heartbeats (which is a topic for another day).
However, once 110 gateway commands are sent within `x < 60` seconds, the ratelimiter waits an additional `60` seconds instead of just waiting for the remaining `60 - x` seconds, which appears to be a bug and slows down chunking significantly in large bots/shards (among other things).

fwiw, removing those two lines has not resulted in being disconnected from the API (which makes sense), and ratelimit durations were around 5-10 seconds instead of 60 seconds, which matches the expected values assuming ~500ms per command. This was also tested by chunking guilds in a large bot (thanks eq).

### Additional Context
(private channels/threads)
https://discord.com/channels/808030843078836254/847513235536216085/935263233512730674
https://discord.com/channels/808030843078836254/935284950230515713/935286193736802344

**Comment by onerandomusername** [comment]
I believe this change has been used by EQ for the last month, we should consider making a pull request to make this change.
