### ISSUE TITLE
consider timeouts on commands.bot_has_permissions() and other check decorators

### ISSUE THREAD

**Issue by onerandomusername** [DisnakeDev/disnake#318]
### Summary

consider timeouts on commands.bot_has_permissions() and other check decorators

### What is the feature request for?

disnake.ext.commands

### The Problem

Bots are affected by timeouts if they don't have the proper permissions. This means that commands.bot_has_permissions is inaccurate if the bot is timed out, which causes scenarios that the decorator is intended to avoid, and can lead to extra 403s that shouldn't exist.

### The Ideal Solution

some kwarg to bot_has_permissions and related decorators named like `ignore_timeout`, with one major change from `permissions_for`: `ignore_timeout` will default to `False`. This is a breaking change, but because timeouts are a breaking change by discord, I think this is a valid incompatible change to make.

### The Current Solution

Pray no one times out the bot so you don't get 403s.

**Comment by shiftinv** [comment]
This should've been fixed by #672, unless an `ignore_timeout` kwarg on the check decorators is still wanted.

**Comment by onerandomusername** [comment]
Versionchanged documentation was not added to #672 so this is still unfixed, but it is now just a documentation change. 🙃
