### ISSUE TITLE
docs: Build and include the examples/ directory in the documentation

### ISSUE THREAD

**Issue by onerandomusername** [DisnakeDev/disnake#324]
### Summary

Build and include the examples/ directory in the documentation

### What is the feature request for?

The documentation

### The Problem

The examples aren't *too* great to access and would be nice if they were more included on the documentation.

Additionally, the API Reference is a huge page and it might make sense to split it into multiple pages.

### The Ideal Solution

Include the examples on the documentation and link to them where objects are used.

**Comment by Victorsitou** [comment]
We already have some examples [here](https://docs.disnake.dev/en/latest/ext/commands/index.html), no?

**Comment by onerandomusername** [comment]
Not all of the examples. I'm thinking something with the https://github.com/DisnakeDev/disnake/tree/master/examples being featured on the docs and perhaps a few pages that embed those files. Its quite possible to do with sphinx if we want to do it.

**Comment by Victorsitou** [comment]
I don't think these examples are really used? The documentation already has some good examples (they are missing a few)

**Comment by onerandomusername** [comment]
We link to them a lot in the support guild.

**Comment by Victorsitou** [comment]
You're right, now that I see it, there are missing examples about components in the documentation, that change would be good.

I don't think the other examples (those that are located in examples directory) need to be added in the documentation.
