### ISSUE TITLE
Slash commands callback not getting called when a slash command name has an uppercase letter

### ISSUE THREAD

**Issue by Victorsitou** [DisnakeDev/disnake#336]
### Summary

When creating a slash commands with a name with an uppercase letter, the callback will never be called.

note: this also happens with sub_command_group and sub_command

### Reproduction Steps

1. Create a slash command with a name with an uppercase letter, for example, Send_modal.
2. Run the command on Discord.

### Minimal Reproducible Code

```python
@bot.slash_command(name="Send_modal")
async def modal(inter: disnake.CommandInter):
  ...
```

### Expected Results

The callback to get called.

### Actual Results

The callback isn't called.

### Intents

N/A

### System Information

Tested with master branch.

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

The problem is that when creating `InvokableSlashCommand.body`, `SlashCommand` does `name.lower()`
https://github.com/DisnakeDev/disnake/blob/dbf26a0984c5bd0870a1d2868518d948c2edb6eb/disnake/app_commands.py#L528-L536
 but disnake caches the command with the uppercase name, making it not possible to find the command.
https://github.com/DisnakeDev/disnake/blob/dbf26a0984c5bd0870a1d2868518d948c2edb6eb/disnake/ext/commands/interaction_bot_base.py#L242

Using the reproducible code, `all_slash_commands` will be `{"Send_modal": InvokableSlashCommand}`, making the code below not able to find the `InvokableSlashCommand` since `command_name` is `send_modal`.
https://github.com/DisnakeDev/disnake/blob/dbf26a0984c5bd0870a1d2868518d948c2edb6eb/disnake/ext/commands/interaction_bot_base.py#L1319-L1321

**Comment by solumath** [comment]
Reproduced, can confirm. Had same problem, the slash commands timeouts everytime.
