### ISSUE TITLE
Automatic defer

### ISSUE THREAD

**Issue by xlysander12** [DisnakeDev/disnake#344]
### Summary

Add a way so that every slash command automatically defers

### What is the feature request for?

disnake.ext.commands

### The Problem

Sometimes commands take a little while to execute and, in those times, sometimes the interaction fails because the bot takes too long to answer. That however can be avoided by `defering` the command in question

### The Ideal Solution

The ideal solution would be a way to automatically `defer` every command so that wouldn't be needed to be done in every command (maybe in the `Bot`'s `constructor`?)

### The Current Solution

For now, there is a way to _kinda_ do this that is adding a global check that `defers`, but that looks a little too _sketchy_.

**Comment by thesadru** [comment]
Would be nice if it's set per command. I'd also appreciate automatic ephemeral messages.

**Comment by onerandomusername** [comment]
This can already be implemented with a [pre invoke hook](https://docs.disnake.dev/en/stable/ext/commands/api.html#disnake.ext.commands.Bot.before_slash_command_invoke).
