### ISSUE TITLE
PartialInviteChannel name can be None

### ISSUE THREAD

**Issue by mbaruh** [DisnakeDev/disnake#382]
### Summary

Attempting to cast a PartialInviteChannel's instance to a string will result in a TypeError for an unnamed group DM invite, because there is no channel name.

### Reproduction Steps

- Create an empty group DM, and don't give it a name yet (the title should say "Unnamed")
- Create an invite for it, and get the invite object with `client.fetch_invite`.
- The invite's channel's name should be None.

### Expected Results

The channel name should always be a string, as per https://docs.disnake.dev/en/latest/api.html?highlight=partialinvitechannel#disnake.PartialInviteChannel.name

### Actual Results

The channel's name with the steps above is None, which means the channel's `__str__` returns None, which makes functions like `print` error out: 
```py
TypeError: __str__ returned non-string (type NoneType)
```

### Intents

All of them but presence

### System Information

Linux, Python 3.9.10. Let me know if you can't reproduce it with the info provided.

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

One possible solution would be to just return an empty string. Another would be to return "Unnamed" which is what the Discord client displays in this case for the channel. Either way like the error says `__str__` should always return a string.

**Comment by onerandomusername** [comment]
Thank you for the bug report. I was able to recreate this locally, and should have a pull to fix it shortly.
