### ISSUE TITLE
cooldown is not applied on .sub_command()

### ISSUE THREAD

**Issue by Xemay** [DisnakeDev/disnake#487]
### Summary

Сommand.cooldown() does not change the cooldown for specific slash commands

### Reproduction Steps

1. Create any slash command with command.cooldown()
2. Create a sub command with any cooldown
3.  Run code

### Minimal Reproducible Code

```python
@commands.slash_command()
@commands.cooldown(1, 100)
    async def parent(self, inter):...

@parent.sub_command()
  async def sub_without_cooldown(self, inter):
      # something...

@parent.sub_command()
@commands.cooldown(1, 150)
   async def sub_example(self, inter):
        # something...
```

### Expected Results

Sub_without_cooldown command and other sub commands will have cooldown specified in parent. Sub_example will have another cooldown

### Actual Results

Sub_example has the same cooldown as parent

### Intents

all

### System Information

Disnake: 2.5.0a
Python 3.10.1
Windows 10

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

I also tried to use dynamic_cooldown but it also doesn't work with subcommands

**Comment by realShamlol** [comment]
Hello there, IIRC, cooldowns have a `type=` parameter that you can use with [commands.BucketType](https://docs.disnake.dev/en/stable/ext/commands/api.html#disnake.ext.commands.BucketType). The last time someone had the same problem, this worked for them and it works for me too.

**Comment by Xemay** [comment]
> 

Hello. unfortunately I just tried it and it didn't work. I used the same and different BucketType in parent and sub_example but it didn't help. Could you show me an example with code?

**Comment by realShamlol** [comment]
> > Hello there, IIRC, cooldowns have a `type=` parameter that you can use with [commands.BucketType](https://docs.disnake.dev/en/stable/ext/commands/api.html#disnake.ext.commands.BucketType). The last time someone had the same problem, this worked for them and it works for me too.
> 
> Hello. unfortunately I just tried it and it didn't work. I used the same and different BucketType in parent and sub_example but it didn't help. Could you show me an example with code?

Something like 
```python
@commands.slash_command()
async def le_cmd(self):
    ...

@le_cmd.sub_command()
@commands.cooldown(1, 40, commands.BucketType.user)
async def cmd_cooldown(self):
    # insert stuff here
```
But also note that on the code that you sent, cooldowns can't work on parent commands, as you possibly know that parent commands will not show if you have subcommands. Ref: 
![image](https://user-images.githubusercontent.com/80943664/164304891-a92bdc3f-9446-48a7-9c9c-f2d6354103fd.png)

**Comment by Xemay** [comment]
> > > Hello there, IIRC, cooldowns have a `type=` parameter that you can use with [commands.BucketType](https://docs.disnake.dev/en/stable/ext/commands/api.html#disnake.ext.commands.BucketType). The last time someone had the same problem, this worked for them and it works for me too.
> > 
> > 
> > Hello. unfortunately I just tried it and it didn't work. I used the same and different BucketType in parent and sub_example but it didn't help. Could you show me an example with code?
> 
> Something like
> 
> ```python
> @commands.slash_command()
> async def le_cmd(self, inter: CommandInteraction):
>     ...
> 
> @le_cmd.sub_command()
> @commands.cooldown(1, 40, commands.BucketType.user)
> async def cmd_cooldown(self, inter: CommandInteraction):
>     # insert stuff here
> ```
> 
> But also note that on the code that you sent, cooldowns can't work on parent commands, as you possibly know that parent commands will not show if you have subcommands. Ref: ![image](https://user-images.githubusercontent.com/80943664/164304891-a92bdc3f-9446-48a7-9c9c-f2d6354103fd.png)

Thank you very much!

**Comment by realShamlol** [comment]
You are very welcome! Please close the issue if your problem has been solved :)

**Comment by Xemay** [comment]
> > > Hello there, IIRC, cooldowns have a `type=` parameter that you can use with [commands.BucketType](https://docs.disnake.dev/en/stable/ext/commands/api.html#disnake.ext.commands.BucketType). The last time someone had the same problem, this worked for them and it works for me too.
> > 
> > 
> > Hello. unfortunately I just tried it and it didn't work. I used the same and different BucketType in parent and sub_example but it didn't help. Could you show me an example with code?
> 
> Something like
> 
> ```python
> @commands.slash_command()
> async def le_cmd(self, inter: CommandInteraction):
>     ...
> 
> @le_cmd.sub_command()
> @commands.cooldown(1, 40, commands.BucketType.user)
> async def cmd_cooldown(self, inter: CommandInteraction):
>     # insert stuff here
> ```
> 
> But also note that on the code that you sent, cooldowns can't work on parent commands, as you possibly know that parent commands will not show if you have subcommands. Ref: ![image](https://user-images.githubusercontent.com/80943664/164304891-a92bdc3f-9446-48a7-9c9c-f2d6354103fd.png)

Thank you very much!
