### ISSUE TITLE
Slash Commands not Globalising

### ISSUE THREAD

**Issue by TwelfthDoctor1** [DisnakeDev/disnake#499]
### Summary

I have been trying to get slash commands to work in DMs, after getting some help over in the Discord Server with some non test-guilds test, it seems that my slash commands are not being registered. Currently not sure why.

### Reproduction Steps

I just followed the steps to make the slash commands, except that the remainder of the function is housed in other modules (though that shouldn't be an issue).

The bot has the applications.command scope and has all Intents.

### Minimal Reproducible Code

```python
class TD1BotClient(commands.Bot):
    """
    Subclass of the discord.py/disnake Bot Class.
    """
    def __init__(self):
        super().__init__(
            command_prefix=commands.when_mentioned_or("~", "?", "!"),
            description="""
            This is a test help command.

            Bot Prefixes: ~ OR ! OR ?
            """,
            owner_id=os.getenv("DEVELOPER_ID"),
            test_guilds=[604082560217120778, 569137415051280404, 949322786713788426],
            intents=INTENTS,
            sync_commands_debug=True
        )
        # self.InternalHandler = TD1BotClient()

        self.master_logger = CoreFunctionService()
        self.dt = datetime.datetime


@client.slash_command(name="ping", description="Gets the network latency of the bot.")
async def ping_slash(inter: ApplicationCommandInteraction):
    return await client.ping_cmd(inter)
# Remainder of code is housed in another module
```

### Expected Results

I would have expected my slash commands to work on all servers and DMs.

### Actual Results

However, it only works on test servers that are listed in the Bot test_guilds.

### Intents

Intents.all()

### System Information

- Python v3.9.0-final
- disnake v2.4.0-final
    - disnake pkg_resources: v2.4.0
- aiohttp v3.7.4.post0
- system info: Darwin 21.5.0 Darwin Kernel Version 21.5.0: Thu Apr 21 19:51:22 PDT 2022; root:xnu-8020.120.68.131.2~2/RELEASE_X86_64

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

I am not sure if it is a Discord Application issue or if it is something else, I have already sought help in the Discord server, though no one was sure of the issue causing it at the time of writing this bug issue.

**Comment by onerandomusername** [comment]
This works as expected. 

`test_guilds` is mutually exclusive with global commands. If you provide `test_guilds` this means that *all* commands are registered as guild command in the provided guilds. There are no global commands when using `test_guilds`.

To fix this problem, and have global commands, simply remove the `test_guilds` parameter from your bot.
