### ISSUE TITLE
OSError: [Errno 22] Invalid argument

### ISSUE THREAD

**Issue by Nebulizer1213** [DisnakeDev/disnake#507]
### Summary

ever since I have started running my bot on my ubuntu server i have been getting this error OSError: [Errno 22] Invalid argument

### Reproduction Steps

The errors occurs randomly

### Expected Results

I would expect for my bot to run normally

### Actual Results

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/aiohttp/connector.py", line 1154>
  File "/usr/local/lib/python3.9/dist-packages/aiohttp/connector.py", line 880,>
  File "/usr/local/lib/python3.9/dist-packages/aiohttp/resolver.py", line 33, i>
  File "/usr/lib/python3.9/asyncio/base_events.py", line 856, in getaddrinfo
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
OSError: [Errno 22] Invalid argument

### Intents

all

### System Information

- Python v3.9.5-final
- disnake v2.4.0-final
    - disnake pkg_resources: v2.4.0
- aiohttp v3.8.1
- system info: Linux 5.13.0-35-generic #40~20.04.1-Ubuntu SMP Mon Mar 7 09:18:32 UTC 2022

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by lol219** [comment]
Try to update your disnake version 2.5.0 then try again, or can you show the code smh

**Comment by Nebulizer1213** [comment]
> Try to update your disnake version to 2.5.0 then try again, or can you show the code smh

The error happens randomly, so I can't send the code for a specific command or event. I am not going to send the code for my whole bot because it is multiple files and I don't think it will be any help. I think the problem has to do with switching to linux because the bot worked fine on windows.

**Comment by onerandomusername** [comment]
Without more information, we are unable to help. Please consider asking your question in https://discord.gg/disnake or provide more information.
