### ISSUE TITLE
error with test bot

### ISSUE THREAD

**Issue by tigra323** [DisnakeDev/disnake#527]
### Summary

error with test bot

### Reproduction Steps

1) Have windows
2) Download repository and unzip it
3) Goto test_bot folder
4) Edit main.py (add token in end)
5) Run main.py

### Expected Results

Bot launch

### Actual Results

disnake: 2.5.1

Traceback (most recent call last):
  File "C:\Users\tigra323\Desktop\disnake-master\test_bot\main.py", line 108, in <module>
    bot = TestBot()
  File "C:\Users\tigra323\Desktop\disnake-master\test_bot\main.py", line 30, in __init__
    self.i18n.load("test_bot/locale")
  File "C:\Program Files (x86)\Python39-32\lib\site-packages\disnake\i18n.py", line 403, in load
    raise RuntimeError(f"Path '{path}' does not exist or is not a directory/file")
RuntimeError: Path 'test_bot\locale' does not exist or is not a directory/file

### Intents

intents=disnake.Intents.all()

### System Information

- Python v3.9.9-final
- disnake v2.5.1-final
    - disnake pkg_resources: v2.5.1
- aiohttp v3.8.1
- system info: Windows 10 10.0.19044

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by howkawgew** [comment]
it looks like a problem with $PYTHOPATH env variable...

**Comment by tigra323** [comment]
I just deleted this line, and wrote a issues. I'm not the only one having these problems. There was also a similar error in load_all_extensions, but I replaced it with load_extensions
