### ISSUE TITLE
A context menu from the example is not appearing

### ISSUE THREAD

**Issue by 6r1d** [DisnakeDev/disnake#53]
### Summary

A context menu from the main page example doesn't appear

### Reproduction Steps

Hello. I've moved to `disnake` today to test the context menu functionality I wasn't able to see in with [Discord-interactions](https://github.com/goverfl0w/discord-interactions#context-menus).

I have used my Discord token, copied the server ID in Discord and I don't see any changes in the context menu of a Discord message.
I expected to see an item like `avatar`, but there's none.
No exception to see why that did not happen, as well.

It doesn't matter if the decorator is located in `__init__` or `on_ready`, it also doesn't matter if I set up a name for a command like here:

```python
@self.user_command(name="Avatar") # optional
async def avatar(inter: disnake.UserCommandInteraction):
    # inter.target is the user you clicked on
    emb = disnake.Embed(title=f"{inter.target}'s avatar")
    emb.set_image(url=inter.target.display_avatar.url)
    await inter.response.send_message(embed=emb)
```

The only difference is how I construct the class, but everything else works.

### Minimal Reproducible Code

```python
GUILD_ID = 765671
DISCORD_TOKEN = 'I-am-a-bot-token'

class TestInterface(commands.Bot):
    
    def __init__(self):
        super().__init__(test_guilds=[GUILD_ID])

    async def on_ready(self):
        @self.user_command()
        async def avatar(inter):
            embed = disnake.Embed(title=str(inter.author))
            embed.set_image(url=inter.author.avatar.url)
            await inter.response.send_message(embed=embed)

def main():
    client = TestInterface()
    try:
        client.loop.run_until_complete(client.start(DISCORD_TOKEN)
    except KeyboardInterrupt:
        client.loop.run_until_complete(client.close())
    finally:
        client.loop.close()
```

### Expected Results

I expect to be able to right-click a message, see a context menu and use an "avatar" item in it.

### Actual Results

I see no new items in a message context menu.

### Intents

I don't know about them, sorry

### System Information

- Python v3.8.12-final
- disnake v2.1.2-alpha
    - disnake pkg_resources: v2.1.2
- aiohttp v3.7.4
- system info: Linux 4.15.0-159-generic #167-Ubuntu SMP Tue Sep 21 08:55:05 UTC 2021

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by EQUENOS** [comment]
You're supposed to use this decorator after the definition of the `client` variable, using `@client.user_command`
Also you can call `client.run(DISCORD_TOKEN)` instead of `try-except-finally` construction

**Comment by 6r1d** [comment]
Thanks, makes sense.

> Also you can call client.run(DISCORD_TOKEN) instead of try-except-finally construction

Yes, it's just my preference, because I want to use some other AsyncIO features there.
