### ISSUE TITLE
cogs

### ISSUE THREAD

**Issue by Saadelamali** [DisnakeDev/disnake#551]
### Summary

The slash commands in cogs dont work. It used to work fine 

### Reproduction Steps

just loading the cogs

### Expected Results

shows the slash commands in the (test_guilds)

### Actual Results

The commands work fine but slash commands dont even show up in the specific guild (test_guilds)

### Intents

members

### System Information

```markdown
- Python v3.10.2-final
- disnake v2.5.1-final
    - disnake pkg_resources: v2.5.1
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.19044
```

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by helish88** [comment]
ask for help here https://discord.gg/disnake

**Comment by helish88** [comment]
I'm sorry, I don't have telepathy, I can't see your code.

**Comment by ironman9356** [comment]
What is the error in console ?

**Comment by helish88** [comment]
```
except Exception:
      pass
```
change to 
```py
except Exception as e:
      print(e)

**Comment by Saadelamali** [comment]
Thats not the issue doe

**Comment by ironman9356** [comment]
Just do it and send the issue

**Comment by Saadelamali** [comment]
it will print "cogs.slashcommands is already loaded/not loaded"

**Comment by Saadelamali** [comment]
do you even know what's my issue 

> Just do it and send the issue

**Comment by Saadelamali** [comment]
> ```python
>   @add.error
>   async def add_error(self, ctx, error):
>      if isinstance(error, commands.NotOwner):
>        await ctx.send("<:zeroon1no:866375710130044968> You can't use this.", ephemeral=True)```
> ```
> 
> add a else
> 
> ```python
>   @add.error
> async def add_error(self, ctx, error):
>   if isinstance(error, commands.NotOwner):
>     await ctx.send("<:zeroon1no:866375710130044968> You can't use this.", ephemeral=True)
>   else:
>       print(error)
> ```

omg thats not the issue

**Comment by helish88** [comment]
read this amazing [guide](https://guide.disnake.dev/popular-topics/errors)

**Comment by helish88** [comment]
> > ```python
> >   @add.error
> >   async def add_error(self, ctx, error):
> >      if isinstance(error, commands.NotOwner):
> >        await ctx.send("<:zeroon1no:866375710130044968> You can't use this.", ephemeral=True)```
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > add a else
> > ```python
> >   @add.error
> > async def add_error(self, ctx, error):
> >   if isinstance(error, commands.NotOwner):
> >     await ctx.send("<:zeroon1no:866375710130044968> You can't use this.", ephemeral=True)
> >   else:
> >       print(error)
> > ```
> 
> omg thats not the issue

omg, you don't see any error when you're trying to use this command,. bruh
