### ISSUE TITLE
Cannot install on raspberry pi 4

### ISSUE THREAD

**Issue by KarsonTheFoxx** [DisnakeDev/disnake#587]
### Summary

Raspberry pi 4's running raspberryPIOS seem incapable of using this fork using `python3 -m pip install -U disnake`

### Reproduction Steps

open pi's terminal and update its systems `sudo apt update && sudo apt upgrade -y`
attempt to install disnake `python3 -m pip install -U disnake`

### Minimal Reproducible Code

```python
sudo apt update && sudo apt upgrade -y
python3 -m pip install -U disnake
```

### Expected Results

disnake to be installed

### Actual Results

Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting disnake
  Could not find a version that satisfies the requirement disnake (from versions: )
No matching distribution found for disnake

### Intents

N/A

### System Information

```markdown
python3.8
Raspian 10
```

### Checklist

- [X] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by onerandomusername** [comment]
Hi, would you please run `python3 -m pip -V` and send the full output?

**Comment by KarsonTheFoxx** [comment]
same output

**Comment by onerandomusername** [comment]
Sorry, I don't see the full output of that command anywhere in your issue. Please share the entire output.

**Comment by KarsonTheFoxx** [comment]
Usage:   
  /usr/bin/python3 -m pip <command> [options]

Commands:
  install                     Install packages.
  download                    Download packages.
  uninstall                   Uninstall packages.
  freeze                      Output installed packages in requirements format.
  list                        List installed packages.
  show                        Show information about installed packages.
  check                       Verify installed packages have compatible dependencies.
  config                      Manage local and global configuration.
  search                      Search PyPI for packages.
  wheel                       Build wheels from your requirements.
  hash                        Compute hashes of package archives.
  completion                  A helper command used for command completion.
  help                        Show help for commands.

General Options:
  -h, --help                  Show help.
  --isolated                  Run pip in an isolated mode, ignoring
                              environment variables and user configuration.
  -v, --verbose               Give more output. Option is additive, and can be
                              used up to 3 times.
  -V, --version               Show version and exit.
  -q, --quiet                 Give less output. Option is additive, and can be
                              used up to 3 times (corresponding to WARNING,
                              ERROR, and CRITICAL logging levels).
  --log <path>                Path to a verbose appending log.
  --proxy <proxy>             Specify a proxy in the form
                              [user:passwd@]proxy.server:port.
  --retries <retries>         Maximum number of retries each connection should
                              attempt (default 5 times).
  --timeout <sec>             Set the socket timeout (default 15 seconds).
  --exists-action <action>    Default action when a path already exists:
                              (s)witch, (i)gnore, (w)ipe, (b)ackup, (a)bort).
  --trusted-host <hostname>   Mark this host as trusted, even though it does
                              not have valid or any HTTPS.
  --cert <path>               Path to alternate CA bundle.
  --client-cert <path>        Path to SSL client certificate, a single file
                              containing the private key and the certificate
                              in PEM format.
  --cache-dir <dir>           Store the cache data in <dir>.
  --no-cache-dir              Disable the cache.
  --disable-pip-version-check
                              Don't periodically check PyPI to determine
                              whether a new version of pip is available for
                              download. Implied with --no-index.
  --no-color                  Suppress colored output

**Comment by KarsonTheFoxx** [comment]
not what i expected

**Comment by KarsonTheFoxx** [comment]
oh i just noticed, my pip is for py3.7, how do i update this?

**Comment by shiftinv** [comment]
Raspbian/Debian 10 ships with Python 3.7, which means unless you manually installed a more recent version, the version you're trying to use is unsupported. You could upgrade to Raspbian 11 which comes with Python 3.9 and should work just fine.

**Comment by KarsonTheFoxx** [comment]
> Raspbian/Debian 10 ships with Python 3.7, which means unless you manually installed a more recent version, the version you're trying to use is unsupported. You could upgrade to Raspbian 11 which comes with Python 3.9 and should work just fine.

would using ubuntu work also? i was planning on switching it

**Comment by onerandomusername** [comment]
You should be able to use [pyenv](https://github.com/pyenv/pyenv#installation) and not have to update your entire operating system to have a more up-to-date python. The minimum supported python version by disnake is 3.8
