### ISSUE TITLE
Nsfw support for application commands

### ISSUE THREAD

**Issue by lol219** [DisnakeDev/disnake#591]
### Summary

This is a feature request to add the nsfw support for application commands into disnake

### What is the feature request for?

The core library

### The Problem

Implementing the new feature 

### The Ideal Solution

Implementing the new feature (it's just a boolean field in the command object, that feature was mentioned in discord api roadmap)

**Comment by onerandomusername** [comment]
That feature currently hasn't been released in full by Discord, but we have a pr already in the works. If you would like to test it works as desired that would be quite beneficial.

**Comment by lol219** [comment]
Sure
