### ISSUE TITLE
Slash commands not syncing after being added on_ready listener

### ISSUE THREAD

**Issue by toBeOfUse** [DisnakeDev/disnake#618]
### Summary

I would like to be able to add slash commands for my bot after the bot logs in. However, adding slash commands in the on_ready listener for the bot is not working.

### Reproduction Steps

 - Created an InteractionBot
 - Made an on_ready listener that adds a slash command using the @slash_command decorator

### Minimal Reproducible Code

```python
import logging
logger = logging.getLogger()
logger.setLevel(logging.DEBUG)
handler = logging.FileHandler(filename='discord.log', encoding='utf-8', mode='w')
handler.setFormatter(logging.Formatter('%(asctime)s: %(levelname)s: %(name)s: %(message)s'))
logger.addHandler(handler)

from disnake import ApplicationCommandInteraction
from disnake.ext.commands import InteractionBot

bot = InteractionBot(test_guilds=[], sync_commands=True)

@bot.listen("on_ready")
async def register_slash_commands():
    logger.debug("registering slash commands in on_ready listener")
    @bot.slash_command(description="say hello")
    async def hello(act: ApplicationCommandInteraction):
        await act.response.send_message("hello!")

bot.run("token")
```

### Expected Results

I expected the added slash command to show up on the server.

### Actual Results

The slash command never shows up on the server; in the logs, there is an attempt to sync slash commands, but it happens before my on_ready listener adds mine. I perused the code in InteractionBotBase.@slash_command but I did not find any place where it initiates synchronization; it just calls add_slash_command which then adds the slash command to an internal dict.

### Intents

InteractionBot with default Intents

### System Information

```markdown
- Python v3.10.2-final
- disnake v2.5.1-final
    - disnake pkg_resources: v2.5.1
- aiohttp v3.8.1
- system info: Windows 10 10.0.19043
```

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

This is related to #468; finishing that would probably fix this. I'm honestly not 100% sure if this is a feature request or a bug report but on the Discord I was informed that slash commands are supposed to be synchronized automatically so here you go. One workaround I found is to call `bot._schedule_app_command_preparation()` to force slash command synchronization but I don't want to rely on undocumented methods.

**Comment by Chromosomologist** [comment]
This actually is not a bug. First and foremost, the default implementation checks for all loaded commands when the bot logs in, and does one bulk overwrite call to make sure all registered commands are synced with discord; and anything on discord's end that is out-of-sync is edited/removed accordingly. All of this happens before the `ready`-event is fired, hence the command you defined there does not show up.

Now, there are two options. First (not recommended in this case, I'll explain why later), you can manually sync the command using `Client.create_global_command`/`Client.create_guild_command` (note that `Bot` is a subclass of `Client`). The reason I say this isn't recommended is that you're trying to work inside the `ready`-event. This event is called every time the bot reconnects to discord-- it could temporarily lose connection, etc. This would lead the bot to try and add the command again, which would then proceed to error out. Similarly, if you were to restart your bot, the initial sync would remove this command, and it would then be re-added inside the `on_ready`-listener; though this can be disabled.

It's overall much better practice to, as is shown in our numerous [examples](https://github.com/DisnakeDev/disnake/blob/master/examples/slash_commands/param.py) on slash commands, define them on the top-level right alongside the bot:
```py
bot = commands.Bot(...)


@bot.slash_command()
async def good_practice(inter: disnake.CommandInteraction):
    await inter.response.send_message("Good stuff.")


bot.run()
```
This would allow the automatic sync to pick up on it as intended and do the work for you, without any of the shenanigans you have to account for when trying to load your command inside the `ready`-event.
