### ISSUE TITLE
Add localisation example

### ISSUE THREAD

**Issue by ItsAleph** [DisnakeDev/disnake#633]
### Summary

Add localisation example bot

### What is the feature request for?

The documentation

### The Problem

Localisation is a brand-new feature, both on disnake's and Discord's side, and while documentation exists, some may learn faster by looking at the example bot.

### The Ideal Solution

Add a simple bot where most often used ways of creating localisation messages are shown as a separate commands.

### The Current Solution

Docs or N/A

### Additional Context

N/A

**Comment by onerandomusername** [comment]
There is already a [localization example](https://github.com/DisnakeDev/disnake/blob/master/examples/localizations.py).
