### ISSUE TITLE
Support new thread and message attributes (position, message_count, total_message_sent)

### ISSUE THREAD

**Issue by onerandomusername** [DisnakeDev/disnake#640]
### Summary

https://github.com/discord/discord-api-docs/pull/5206

### What is the feature request for?

The core library

### The Feature

`Message.position`, should probably default to None outside of forum channels, or we could think about using `-1` so its always an integer.
`Thread.message_count`
`Thread.total_message_sent`

However, there is a small implementation detail here: 
Should we increment the `message_count` and `total_message_sent` variables when we receive a `message_create` event for the thread? I believe we should.

In addition, when we receive a message_delete event in a thread, we should decrement `message_count` if the thread is cached whether or not the message is cached.

**Comment by rmblau** [comment]
I shall take a look at this.

**Comment by onerandomusername** [comment]
Assigned you.

**Comment by onerandomusername** [comment]
@rmblau are you still interested in implementing this feature?

**Comment by rmblau** [comment]
Yes I am, I just got back from family vacation and can take a look at it this week.

**Comment by onerandomusername** [comment]
Because there's no progress on this, I'm moving it back to up for grabs.

**Comment by Snipy7374** [comment]
I shall take a look at this.
