### ISSUE TITLE
docs: `i18n` property is not documented on `commands.Bot`

### ISSUE THREAD

**Issue by ItsAleph** [DisnakeDev/disnake#652]
### Summary

`i18n` property missing on `commands.Bot` class

### Reproduction Steps

Clone the repo, build the docs, GOTO `docs/_build/html/ext/commands/api.html` and open it in your browser (Alternatively GOTO https://docs.disnake.dev/en/stable/ext/commands/api.html). You'll see that `i18n` property is missing on `commands.Bot` class reference, while physically exist in library.

### Minimal Reproducible Code

```python
N/A
```

### Expected Results

See the `i18n` property :P

### Actual Results

There is no `i18n` property 

### Intents

N/A

### System Information

```markdown
disnake v2.5.1 and sphinx 4.5.0, other info is not applicable
```

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by ironman9356** [comment]
i think its intentional that its in [disnake.Client](https://docs.disnake.dev/en/stable/api.html?highlight=i18n#disnake.Client.i18n) 
and not in commands.Bot because both are basically the [same](https://github.com/DisnakeDev/disnake/blob/v2.5.1/disnake/ext/commands/bot.py#L57)

**Comment by Enegg** [comment]
[commands.Bot](https://docs.disnake.dev/en/stable/ext/commands/api.html#bot) seems to document most if not all of the attributes of [disnake.Client](https://docs.disnake.dev/en/stable/api.html#client), it doesn't make sense for `i18n` to be left out
