### ISSUE TITLE
feat: Interaction.data

### ISSUE THREAD

**Issue by onerandomusername** [DisnakeDev/disnake#654]
### Summary

Interaction.data attribute to show the provided data.

### What is the feature request for?

The core library

### The Problem

Can't assume the `data` attribute will always exist even though every subclass already includes it.

### The Ideal Solution

Provide the data information on the parent if it isn't defined by the subclasses.

### The Current Solution

`getattr(inter, "data", {})`

**Comment by EmreTech** [comment]
I would like to implement this!

**Comment by onerandomusername** [comment]
you've been assigned, @EmreTech
