### ISSUE TITLE
issue with accounts token

### ISSUE THREAD

**Issue by adam1231231** [DisnakeDev/disnake#682]
### Summary

client.run(token, bot= False) isn't working

### Reproduction Steps

i want to use a user's account's token instead of a bot, i tried it and it worked on the discord.py module, but didn't on disnake for some reason, is it moved to somewhere else? or is it gone now?

### Expected Results

expected my script to work on the user account normally, but it only works on bots and with bots token

### Actual Results

it didn't work

### Intents

not using any

### System Information

```markdown
- Python v3.10.5-final
- disnake v2.5.2-final
    - disnake pkg_resources: v2.5.2
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.22000
```

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by ItsAleph** [comment]
User accounts are not supported by disnake, nor they will in d.py 2.0

**Comment by onerandomusername** [comment]
User bots are no longer supported and are against the terms of service.
