### ISSUE TITLE
read values from a Dropdown inside a Modal

### ISSUE THREAD

**Issue by MakiRollDev** [DisnakeDev/disnake#703]
### Summary

the possibility of using a dropdown component in a modal

### What is the feature request for?

The core library

### The Problem

I have not managed to get modals with dropdown to work so i assume the functionality does not yet exist (i am not sure if maybe discords api doesnt have it or it its just disnake)

### The Ideal Solution

the ideal solution would be me just doing the Implantation wrong

**Comment by EmreTech** [comment]
Currently, Select Menus in Modals haven't been officially released. They work fine on Desktop but have problems on Mobile.

**Comment by CuteNickychan** [comment]
Okay and how would I retrieve the values from a dropdown inside a modal?

**Comment by helish88** [comment]
#611

**Comment by CuteNickychan** [comment]
ahh so its not actually supported yet

**Comment by shiftinv** [comment]
You can technically access the raw component data already, assuming you're using the master branch.
Nevertheless, support for selects in modals on mobile is still wip - #611 is primarily waiting for Discord to implement the feature on all platforms.

**Comment by CuteNickychan** [comment]
okay tyvm

**Comment by shiftinv** [comment]
https://github.com/DisnakeDev/disnake/pull/611#issuecomment-1463770255
