### ISSUE TITLE
[meta] issues with required CI checks

### ISSUE THREAD

**Issue by shiftinv** [DisnakeDev/disnake#819]
Started noticing two distinct CI issues recently with how our checks and branch protection rules work, not exactly sure what's causing them yet.

### 1
The [changelog](https://github.com/DisnakeDev/disnake/blob/master/.github/workflows/changelog.yaml) workflow sometimes(?) just doesn't run after creating a PR, it gets stuck in "expected" indefinitely.

Due to the concurrency rules only one instance of that job should run at a time, with the other ones automatically being canceled. However it seems like they're cancelling each other, resulting in not a single one running to completion.

I believe this worked fine for a while and only started happening recently, which might indicate a GitHub bug or edge case, no clue.

![image](https://media.discordapp.net/attachments/847513235536216085/1033044903342649404/unknown.png)

### 2
Pushing to an internal PR naturally triggers all checks that run on `push` and `pull_request` events.
Like the other jobs, the [check](https://github.com/DisnakeDev/disnake/blob/b37240ff43736077a30b7451024463ee1af8b8d3/.github/workflows/lint-test.yml#L281) job gets skipped on the `pull_request` trigger for internal PRs, since the `push` event already runs the same stuff.

Since the `check (push)` job depends on other jobs and doesn't run (or even get queued) until they're finished, and the `check (pull_request)` job gets skipped, there's a window where the requirements set in the branch protection rules are fulfilled (as skipped checks are valid) and the PR gets merged even though some jobs aren't finished yet.

![image](https://media.discordapp.net/attachments/847513235536216085/1033372985987440710/unknown.png)

For example, [this](https://github.com/DisnakeDev/disnake/actions/runs/3303427194/jobs/5451336902) pytest job finished at 13:32:34, while the PR had already been [merged](https://api.github.com/repos/DisnakeDev/disnake/issues/791/events) at 13:32:16.

**Comment by onerandomusername** [comment]
It looks like if we change some of our workflows and tighten them up a bit as shown [here](https://github.com/aio-libs/aiohttp/blob/71ae610e4d8350f1f1f121164b75ce3ad78d7902/.github/workflows/ci.yml#L1-L18) we should solve the issue, since it would cancel the workflow instead of skipping it.

**Comment by shiftinv** [comment]
Moved the unresolved part of this issue to a new one, #937.
