### ISSUE TITLE
add new properties on `disnake.File` class

### ISSUE THREAD

**Issue by Snipy7374** [DisnakeDev/disnake#839]
### Summary

Implement new properties and methods for the `disnake.File` class

### What is the feature request for?

The core library

### The Problem

Currently `disnake.File` doesn't support some operations. It would be great to implement new properties (such as `closed` that is already accessible but not really user-friendly) and new methods (such as an `__eq__` etc...)

### The Ideal Solution

Implement `__eq__`, `closed` etc... on `disnake.File`

### The Current Solution

Cry about it.

`closed` is currently accessible through `disnake.File.fp.closed`

**Comment by EmreTech** [comment]
Grammar police here.

>  properties/attributes and methods
properities, attributes

> some operations.
some user-friendly operations.

> such as `closed` that is alredy accesible
such as `closed` that is already accessible

> `closed` etc
`closed`, etc
