### ISSUE TITLE
List event reference in the core library

### ISSUE THREAD

**Issue by Enegg** [DisnakeDev/disnake#895]
### Summary

As title states

### What is the feature request for?

The core library

### The Problem

Whenever a need to use `Client.wait_for` appears, there's no way to figure the relevant event name from within library's code; they are listed only in the docs.

### The Ideal Solution

Create string enums for each of relevant event groups, ideally with each member having a docstring describing similar info as can be found in the docs. Having something like that embedded in the code allows for the use of autocompletion.
```py
class InteractionEvent(str, Enum):
    button_click = "button_click"
    """Called when a button is clicked."""
    dropdown = "dropdown"
    """Called when a select menu is clicked."""
```
![image](https://user-images.githubusercontent.com/42005170/206939671-66ab70a6-34d2-41d4-83a5-5a700cd56dd6.png)

### The Current Solution

Writing own enum, memorizing each event, or coping with scrolling down the docs.

**Comment by Chromosomologist** [comment]
Hard agree. While we're at it, I would propose to rework listeners such that the `on_` prefix is no longer necessary (we'd still allow it to remain compatible). This way, these enums could be used both in `Client.wait_for` and in `Bot.listen`.

**Comment by Victorsitou** [comment]
Additionally, we could probably mention what event is triggered when calling any route, such as Discord Docs.
![image](https://user-images.githubusercontent.com/67214928/206941076-de8fa430-dd65-4b0c-b514-6be94cd06b8a.png)
