### ISSUE TITLE
`Cog.add_command`, `.remove_command`, etc.

### ISSUE THREAD

**Issue by shiftinv** [DisnakeDev/disnake#900]
### Summary

see title.

### What is the feature request for?

disnake.ext.commands

### The Problem

There's currently no proper way of dynamically adding/removing commands from cogs, other than directly messing around with internal fields like `__cog_commands__`.

### The Ideal Solution

New methods like `Cog.add_command`, `.remove_command`, as well as complementary ones for slash/user/message application commands.

### The Current Solution

modifying `__cog_commands__`, which isn't documented

### Additional Context

suggested here: https://canary.discord.com/channels/808030843078836254/913779868985090089/1058180711095484416

**Comment by Snipy7374** [comment]
I shall take a look

**Comment by shiftinv** [comment]
After some discussion, I don't think we'll be adding this; there are too many moving parts already in the way cogs work, and this would likely only complicate things.
Cog command callbacks are instance methods, meaning they should accept a `self` parameter, which makes [defining such a method outside of a cog](https://canary.discord.com/channels/808030843078836254/913779868985090089/1064250995472879757) unintuitive.

Currently, the proper solution to the original issue of grouping commands would be using `extras` as outlined here: https://canary.discord.com/channels/808030843078836254/913779868985090089/1064287849467367555 (more context around that message too).
