### ISSUE TITLE
Duplicated disnake.disnake in Event Reference for commands framework in docs

### ISSUE THREAD

**Issue by Exenifix** [DisnakeDev/disnake#944]
### Summary

Search page results and link fragment identifiers (e.g. disnake.disnake.ext.commands.on_slash_command_error)

### Reproduction Steps

https://docs.disnake.dev/en/latest/search.html?q=disnake.disnake
Issue persists for stable docs version as well

![image](https://user-images.githubusercontent.com/89513380/220128847-f437aed7-3dfa-466a-b2e3-401dedc8eedb.png)

### Expected Results

Normal fragment identifiers without duplicated `disnake.disnake`, e.g. `disnake.ext.commands.on_slash_command_error`

### Actual Results

Duplicated fragment identifiers, e.g. `disnake.disnake.ext.commands.on_slash_command_error`

### Intents

Unrelated

### System Information

```markdown
Unrelated
```

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by onerandomusername** [comment]
Thanks, this should be fixed as a part of #722, which has a preview available here: https://disnake--722.org.readthedocs.build/en/722/
