### ISSUE TITLE
Message property inside Interaction

### ISSUE THREAD

**Issue by contanger** [DisnakeDev/disnake#972]
### Summary

Message property inside Interaction

### What is the feature request for?

disnake.ext.commands

### The Problem

It becomes easier to interact with the original message by dropdown lists and buttons

### The Ideal Solution

Add the message property to the interaction by making it an optional parameter. Using message search via `_state` or scan via `Message` class

Like for example:
```py
self.message: Optional[Message]

try:
    message = data["message"] # type: ignore

    self.message = self._state._get_message(int(message["id"])) or Message(
        state=self._state, channel=self.channel, data=message
    )
except KeyError:
    self.message = None
```

**Comment by onerandomusername** [comment]
This is already supported.

Interactions started on components have [`MessageInteraction.message`](https://docs.disnake.dev/en/stable/api.html#disnake.MessageInteraction.message)

If the interaction is from a context menu command, there is [`ApplicationCommandInteraction.target`](https://docs.disnake.dev/en/stable/api.html#disnake.ApplicationCommandInteraction.target)
