### ISSUE TITLE
delete_after in interaction responses

### ISSUE THREAD

**Issue by contanger** [DisnakeDev/disnake#973]
### Summary

Add (or return) delete_after for message changes inside interaction responses

### What is the feature request for?

disnake.ext.commands

### The Problem

It is not possible to specify the deletion of a message after a time

### The Ideal Solution

Add an optional parameter `delete_after:float` to the `edit_message` function inside the `InteractionResponse` class, which will regulate the deletion of the message

**Comment by EQUENOS** [comment]
Consider using [`Interaction.delete_original_response`](https://docs.disnake.dev/en/stable/api.html#disnake.Interaction.delete_original_response)'s `delay` parameter
