### ISSUE TITLE
File class initializer declares support for bytes-object but doesn't actually work with it.

### ISSUE THREAD

**Issue by Alan-Shan** [DisnakeDev/disnake#983]
### Summary

Can't pass bytes to init of the File class.

### Reproduction Steps

file = requests.get(### some url to .png ###)
disnake.File(fp=file.content, filename="image.png")

Response:
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

### Minimal Reproducible Code

```python
file = requests.get("https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx21699-Fkbnkl9ZC6fW.png")
disnake.File(fp=file.content, filename="image.png")

# It'll fail
```

### Expected Results

File instance gets created.

### Actual Results

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

### Intents

Slash Commands

### System Information

```markdown
Python v3.9.0-final
- disnake v2.8.1-final
    - disnake importlib.metadata: v2.8.1
- aiohttp v3.8.4
- system info: Windows 10 10.0.22621 AMD64
```

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

That happens because `def __init__(
        self,
        fp: Union[str, **bytes**, os.PathLike, io.BufferedIOBase],
        filename: Optional[str] = None,
        *,
        spoiler: bool = False,
        description: Optional[str] = None,
    ) -> None:` declares support for bytes. - 
    Permalink to code: https://github.com/DisnakeDev/disnake/blob/b13f9a94df0cd90b5b7b47a009483d816b281690/disnake/file.py#L57
    
But the actual conditioning only checks for io.IOBase. Permalink: https://github.com/DisnakeDev/disnake/blob/b13f9a94df0cd90b5b7b47a009483d816b281690/disnake/file.py#L63
    
Therefore bytes type, support for which is declared in the initializer parameters, is not actually supported.

**Comment by shiftinv** [comment]
`File.__init__` declares support for `bytes` since it's a valid [path-like type](https://docs.python.org/3.11/glossary.html#term-path-like-object) - it gets interpreted as a file path.
To send `bytes` objects as files, use `io.BytesIO(file.content)`.

(additionally, avoid using `requests` in your code and use `aiohttp` instead, which is non-blocking - see [here](https://guide.disnake.dev/faq/coroutines#what-does-blocking-mean) for reasoning)
